<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ChathurangajPC" name="com.synapsys.lmt.test.TestLMTUserAuthorize" tests="1" failures="0" timestamp="2 Feb 2016 07:25:39 GMT" time="5.465" errors="1">
  <testcase name="test_Authorized_User_By_Admin" time="5.465" classname="com.synapsys.lmt.test.TestLMTUserAuthorize">
    <error type="java.lang.Exception">
      <![CDATA[java.lang.Exception
	at com.synapsys.lmt.pages.LMTUserAuthorize.Verify_User_View_in_Grid(LMTUserAuthorize.java:225)
	at com.synapsys.lmt.pages.LMTUserAuthorize.SinglePageSearch(LMTUserAuthorize.java:132)
	at com.synapsys.lmt.pages.LMTUserAuthorize.Search_Grid_for_User_Name(LMTUserAuthorize.java:151)
	at com.synapsys.lmt.test.TestLMTUserAuthorize.test_Authorized_User_By_Admin(TestLMTUserAuthorize.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- test_Authorized_User_By_Admin -->
</testsuite> <!-- com.synapsys.lmt.test.TestLMTUserAuthorize -->
